patreon: disonancias
custom: ["https://www.paypal.com/paypalme/angelmoma", Paypal]
# github: dissonances

# These are supported funding model platforms
# ko_fi: dissonances
# open_collective: dissonances
